name: "Compilation et publication sur Docker Hub"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true 
    - name: "Publication sur Docker Hub"
    - uses: elgohr/Publish-Docker-Github-Action@2.14
      with:
        name: lernpfr/lern
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true
